to_do_list/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
]

to_do_list/notes/urls.py
from django.urls import path

from notes.views import *

app_name = 'notes'

urlpatterns = [
    path('note/list/', NoteListView.as_view(), name='note_list'),
    path('note/create/', NoteCreateView.as_view(), name='note_create'),
    path('note/detail/<int:pk>/', NoteDetailView.as_view(), name='note_detail'),
    path('note/update/<int:pk>/', NoteUpdateView.as_view(), name='note_update'),
    path('note/delete/<int:pk>/', NoteDeleteView.as_view(), name='note_delete'),
]

to_do_list/para/urls.py
from django.urls import path

from para.views import *

app_name = 'para'

urlpatterns = [
    path('area/list/', AreaListView.as_view(), name='area_list'),
    path('area/create/', AreaCreateView.as_view(), name='area_create'),
    path('area/detail/<int:pk>/', AreaDetailView.as_view(), name='area_detail'),
    path('area/update/<int:pk>/', AreaUpdateView.as_view(), name='area_update'),
    path('area/delete/<int:pk>/', AreaDeleteView.as_view(), name='area_delete'),
    path('project/list/', ProjectListView.as_view(), name='project_list'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/detail/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/update/<int:pk>/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/delete/<int:pk>/', ProjectDeleteView.as_view(), name='project_delete'),
    path('resource/list/', ResourceListView.as_view(), name='resource_list'),
    path('resource/create/', ResourceCreateView.as_view(), name='resource_create'),
    path('resource/detail/<int:pk>/', ResourceDetailView.as_view(), name='resource_detail'),
    path('resource/update/<int:pk>/', ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/delete/<int:pk>/', ResourceDeleteView.as_view(), name='resource_delete'),
    path('dashboard/', DashBoardView.as_view(), name='dashboard'),
]

to_do_list/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('list/', views.TaskListView.as_view(), name='task_list'),
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('detail/<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),
]

to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/', include('django.contrib.auth.urls')),
                  path('', include('core.urls')),
                  path('', include('users.urls')),
                  path('tasks/', include('tasks.urls')),
                  path('para/', include('para.urls')),
                  path('notes/', include('notes.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

to_do_list/para/models.py
from io import BytesIO

from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from PIL import Image

from comments.models import Comment
from core.models import ParaTag

User = get_user_model()

STATUS_CHOICES = [
    ('active', 'Active'),
    ('completed', 'Completed'),
    ('on_hold', 'On Hold'),
]

PRIORITY_CHOICES = [
    (1, 'Low'),
    (2, 'Medium'),
    (3, 'High'),
]


class BaseParaModel(models.Model):
    """
    Abstract model containing common fields for all entities (Areas, Projects, Resources,Tasks).
    """

    title = models.CharField(max_length=25, verbose_name='Title')
    description = models.TextField(max_length=1000, verbose_name='Description')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    is_archived = models.BooleanField(default=False, verbose_name='Archive')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    deadline = models.DateField(null=True, blank=True, verbose_name="Deadline")
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2, verbose_name="Priority")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    comments = GenericRelation(Comment, content_type_field='content_type', object_id_field='object_id')
    cover_image = models.ImageField(upload_to='covers/', blank=True, null=True, verbose_name='Cover Image')

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        """
        Overridden method to modify the cover image before saving.
        """

        if self.cover_image:
            img = Image.open(self.cover_image.file)  # Use .file to access the file object
            img = img.resize((300, 365))
            thumb_io = BytesIO()
            img.save(thumb_io, format='JPEG', quality=85)
            thumb_file = ContentFile(thumb_io.getvalue(), name=self.cover_image.name)
            self.cover_image.save(self.cover_image.name, thumb_file, save=False)

        super().save(*args, **kwargs)


class Area(BaseParaModel):
    """
    Model representing an area that groups projects.
    """

    tags = models.ManyToManyField(ParaTag, related_name='areas', blank=True, verbose_name='Tag')

    class Meta:
        verbose_name = 'Area'
        verbose_name_plural = 'Areas'
        ordering = ('title',)

    def __str__(self):
        return f'Area: {self.title}, User: {self.author}'


class Project(BaseParaModel):
    """
    Model representing a project within a specific area.
    """

    area = models.ForeignKey(Area, on_delete=models.SET_NULL, related_name='projects', blank=True, null=True)
    tags = models.ManyToManyField(ParaTag, related_name='projects', blank=True, verbose_name='Tag')

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'
        ordering = ('title',)

    def __str__(self):
        return f'Project: {self.title}, User: {self.author}, Belongs to Area: {self.area}'


class Resource(BaseParaModel):
    """
    Model representing resources associated with projects and areas.
    """

    area = models.ForeignKey(Area, on_delete=models.SET_NULL, related_name='resources', null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='resources', null=True, blank=True)
    tags = models.ManyToManyField(ParaTag, related_name='resources', blank=True, verbose_name='Tag')
    resource_type = models.ForeignKey('ResourceType', on_delete=models.SET_NULL, verbose_name='Resource Type',
                                      null=True, blank=True)

    class Meta:
        verbose_name = 'Resource'
        verbose_name_plural = 'Resources'
        ordering = ('title',)

    def __str__(self):
        return f'Resource: {self.title}, User: {self.author}'


class ResourceType(models.Model):
    """
    Model representing resource types.
    """

    title = models.CharField(max_length=50, unique=True, verbose_name='Тип ресурса')

    def __str__(self):
        return self.title

to_do_list/para/views.py
from django_filters.views import FilterView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, TemplateView

from comments.forms import CommentForm
from comments.utils import handle_comment_creation, handle_comment_deletion, handle_comment_editing, handle_edit_request
from core.models import ParaTag
from notes.models import Note
from para.filters import ParaFilter
from para.forms import AreaForm, ProjectForm, ResourceForm
from para.models import Area, Project, Resource
from tasks.models import Task


class AreaListView(FilterView):
    """
    A view for displaying a filtered and paginated list of areas.

    Methods:
        get_queryset(): Returns the queryset of areas, filtered by project, resource, or area if applicable.
        get_context_data(**kwargs): Extends the context with additional information if needed.
    """

    template_name = 'para/area_list.html'
    model = Area
    ordering = '-id'
    paginate_by = 3
    filterset_class = ParaFilter

    def get_queryset(self):
        """
        Returns a queryset of Area instances, applying filters.
        """

        # Optimizing queries with prefetch_related
        queryset = Area.objects.prefetch_related('projects').order_by(self.ordering)
        # Dynamically assign the model for filtering.
        self.filterset_class.Meta.model = Area
        return self.filterset_class(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs):
        """
        Adds additional context to the view.
        Can be extended if more data needs to be passed to the template.
        """

        context = super().get_context_data(**kwargs)
        return context


class AreaDetailView(DetailView):
    """
    A view for displaying detailed information about a specific Area, including its comments.
    Requires user authentication.

    Methods:
        get_context_data(**kwargs): Adds comments and a comment form to the context.
        post(request, *args, **kwargs): Handles various comment-related actions (creation, editing, deletion).
    """

    template_name = 'para/area_detail.html'
    redirect_url = 'para:area_detail'
    model = Area

    def get_context_data(self, **kwargs):
        """
        Adds additional context to the template, including notes, tasks, and comments.
        """

        context = super().get_context_data(**kwargs)
        area = self.object
        context['area_notes'] = area.notes.order_by('-created')
        context['area_tasks'] = area.tasks.order_by('-created')
        context['comments'] = area.comments.filter(active=True).order_by('-created')
        context['comment_form'] = CommentForm()
        context['editing_comment'] = None
        return context

    def post(self, request, *args, **kwargs):
        """
        Handles the HTTP POST request to manage comments for the Area.

        The method processes the following actions based on the submitted form:
        - Adding a new comment
        - Editing an existing comment
        - Deleting a comment

        Note: Separate handler methods are used for each action, defined in the `comments.utils` module,
        to unify the process for different models.
        """

        self.object = self.get_object()

        if 'submit_comment' in request.POST:
            return handle_comment_creation(request, self.object, self.redirect_url)

        elif 'edit_comment' in request.POST:
            return handle_comment_editing(request, self.object, self.redirect_url)

        elif 'edit' in request.POST:
            context = handle_edit_request(request, self.object, self.get_context_data)
            if context:
                return self.render_to_response(context)

        elif 'delete_comment' in request.POST:
            return handle_comment_deletion(request, self.object, self.redirect_url)

        return self.get(request, *args, **kwargs)


class AreaCreateView(CreateView):
    """
    A view for creating a new area. Requires user authentication.

    Methods:
        form_valid(form): Processes valid form data, assigns the author, saves the image if provided,
        and adds a new tag to the area if specified.
    """

    template_name = 'para/area_create.html'
    model = Area
    success_url = reverse_lazy('para:area_list')
    form_class = AreaForm

    def form_valid(self, form):
        """
        Handles the saving of the area form. Assigns the current user as the areas author,
        saves the cover image if uploaded, and adds a new tag if entered by the user.
        """

        area = form.save(commit=False)
        area.author = self.request.user
        if 'cover_image' in self.request.FILES:
            area.cover_image = self.request.FILES['cover_image']
        area.save()
        form.save_m2m()
        new_tag = form.cleaned_data.get('new_tag')
        if new_tag:
            tag, created = ParaTag.objects.get_or_create(title=new_tag)
            area.tags.add(tag)
        return super().form_valid(form)


class AreaUpdateView(UpdateView):
    """
    A view for updating an existing area. Requires user authentication.
    """

    template_name = 'para/area_create.html'
    model = Area
    form_class = AreaForm
    success_url = reverse_lazy('para:area_list')


class AreaDeleteView(DeleteView):
    """
    A view for deleting an existing area. Requires user authentication.

    Methods:
        dispatch(request, *args, **kwargs): Ensures that only the areas author can access the delete view.
    """

    template_name = 'para/area_confirm_delete.html'
    model = Area
    success_url = reverse_lazy('para:area_list')

    def dispatch(self, request, *args, **kwargs):
        """
        Ensures the user is the author of the area before proceeding with the request.
        """

        get_object_or_404(Area, pk=kwargs['pk'], author=request.user)
        return super().dispatch(request, *args, **kwargs)


# PROJECTS

class ProjectListView(FilterView):
    """
    A view for displaying a filtered and paginated list of projects.

    Methods:
        get_queryset(): Returns the queryset of projects, filtered by project, resource, or area if applicable.
        get_context_data(**kwargs): Extends the context with additional information if needed.
    """

    template_name = 'para/project_list.html'
    model = Project
    ordering = '-id'
    paginate_by = 3
    filterset_class = ParaFilter

    def get_queryset(self):
        """
        Returns a queryset of Project instances, applying filters.
        """

        queryset = Project.objects.all()
        # Dynamically assign the model for filtering.
        self.filterset_class.Meta.model = Project
        return self.filterset_class(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProjectDetailView(DetailView):
    """
    A view for displaying detailed information about a specific Project, including its comments.
    Requires user authentication.

    Methods:
        get_context_data(**kwargs): Adds comments and a comment form to the context.
        post(request, *args, **kwargs): Handles various comment-related actions (creation, editing, deletion).
    """
    template_name = 'para/project_detail.html'
    redirect_url = 'para:project_detail'
    model = Project

    def get_context_data(self, **kwargs):
        """
        Adds additional context to the template, including notes, tasks, and comments.
        """

        context = super().get_context_data(**kwargs)
        project = self.object
        context['project_notes'] = project.notes.order_by('-created')
        context['project_tasks'] = project.tasks.order_by('-created')
        context['comments'] = project.comments.filter(active=True).order_by('-created')
        context['comment_form'] = CommentForm()
        context['editing_comment'] = None
        return context

    def post(self, request, *args, **kwargs):
        """
        Handles the HTTP POST request to manage comments for the Area.

        The method processes the following actions based on the submitted form:
        - Adding a new comment
        - Editing an existing comment
        - Deleting a comment

        Note: Separate handler methods are used for each action, defined in the `comments.utils` module,
        to unify the process for different models.
        """

        self.object = self.get_object()

        if 'submit_comment' in request.POST:
            return handle_comment_creation(request, self.object, self.redirect_url)

        elif 'edit_comment' in request.POST:
            return handle_comment_editing(request, self.object, self.redirect_url)

        elif 'edit' in request.POST:
            context = handle_edit_request(request, self.object, self.get_context_data)
            if context:
                return self.render_to_response(context)

        elif 'delete_comment' in request.POST:
            return handle_comment_deletion(request, self.object, self.redirect_url)

        return self.get(request, *args, **kwargs)


class ProjectCreateView(CreateView):
    """
    A view for creating a new project. Requires user authentication.

    Methods:
        form_valid(form): Processes valid form data, assigns the author, saves the image if provided,
        and adds a new tag to the project if specified.
    """

    template_name = 'para/project_create.html'
    model = Project
    success_url = reverse_lazy('para:project_list')
    form_class = ProjectForm

    def form_valid(self, form):
        """

to_do_list/templates/para/area_confirm_delete.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="d-flex justify-content-center" style="min-height: 200vh;">
    <div class="col-lg-8 text-center">
      <h2>Удалить «{{ object.title }}»?</h2>
      <div style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
           class="card rounded-7 mb-3 p-lg-5">
        <h2 class="fw-bold text-center">
          <span class="text-light">Удаляемый контент:</span>
        </h2>
        <p class="text-center fst-italic"><em>{{ object.description|truncatewords:100 }}<br></em></p>
        <form method="post">
          {% csrf_token %}

          <div class="d-flex justify-content-center mb-3 mt-5">
            <button type="submit" class="btn btn-danger btn-rounded" data-mdb-ripple-init>Удалить</button>
          </div>

        </form>
        <div class="d-flex justify-content-center">
          <a href="{% url 'tasks:task_list' %}?area_id={{ object.id }}" class="btn btn-dark btn-rounded mb-2"
             data-mdb-ripple-init>Список Областей</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}




to_do_list/templates/para/resource_detail.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}





{% block content %}

  <div class="container-fluid">
    <div class="row h-100">
      <!-- Блок с Ресурсом -->
      <div class="col-lg-8 full-height">
        <div style="min-height: 1200px; background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
             class="card rounded-7 mb-3 p-lg-5">
          <h2 class="fw-bold text-center">
            <span class="text-light">{{ object.title }}</span>
          </h2>
          <p class="text-center fst-italic"><em>Deadline: {{ object.deadline }}; Area: {{ object.area.title }}</em>
          </p>
          <p class="text-center fst-italic">
            <em>Теги:
              {% if object.tags.all %}
                {% for tag in object.tags.all %}
                  {{ tag.title }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              {% else %}
                <span>Нет тегов</span>
              {% endif %}
            </em>
          </p>
          <hr class="my-3"/>
          <div class="card-body">
            <p class="text-muted mb-4">
              {{ object.description }}
            </p>

          </div>

          <hr class="my-3"/>
          <div class="d-flex justify-content-center">
            <a href="{% url 'para:resource_list' %}" class="btn btn-dark btn-rounded mb-2" data-mdb-ripple-init>Список
              Ресурсов</a>
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'para:resource_update' object.pk %}" class="btn btn-warning btn-rounded mb-2 me-1"
               data-mdb-ripple-init>
              <i class="bi bi-pencil"></i>
            </a>
            <a href="{% url 'para:resource_delete' object.pk %}" class="btn btn-danger btn-rounded mb-2"
               data-mdb-ripple-init>
              <i class="bi bi-trash"></i>
            </a>
          </div>

          {% comment %}Comments{% endcomment %}
          <hr class="my-3"/>

          {% if editing_comment %}
            <form method="POST">
              {% csrf_token %}
              <input type="hidden" name="comment_id" value="{{ editing_comment.id }}">
              {{ comment_form.text.label }}  <!-- Заголовок поля -->
              {{ comment_form.text }}  <!-- Поле ввода текста с предзаполненным значением -->
              <div class="d-flex justify-content-center mb-3 mt-3">
                <button type="submit" name="edit_comment" class="btn btn-secondary btn-rounded" data-mdb-ripple-init>
                  Редактировать
                </button>
              </div>
            </form>
          {% else %}
            <form method="POST">
              {% csrf_token %}
              {{ comment_form.as_p }}
              <div class="d-flex justify-content-center mb-3 mt-3">
                <button type="submit" name="submit_comment" class="btn btn-secondary btn-rounded" data-mdb-ripple-init>
                  Опубликовать
                </button>
              </div>
            </form>
          {% endif %}

          <br>
          <ul>
            {% for comment in comments %}
              <div class="card mb-3">
                <div class="card-body">
                  <p>{{ comment.text }}</p>
                  <small>Автор: {{ comment.author }} | Дата: {{ comment.created }}</small>
                  <!-- Форма редактирования комментария -->
                  {% if comment.author == request.user %}
                    <form method="post" style="display:inline;">
                      {% csrf_token %}
                      <input type="hidden" name="comment_id" value="{{ comment.id }}">
                      <button type="submit" name="edit" class="btn btn-warning btn-rounded btn-sm"
                              data-mdb-ripple-init>
                        <i class="bi bi-pencil"></i>
                      </button>
                    </form>
                    <!-- Форма удаления комментария -->
                    <form method="post" style="display:inline;">
                      {% csrf_token %}
                      <input type="hidden" name="comment_id" value="{{ comment.id }}">
                      <button type="submit" name="delete_comment" class="btn btn-danger btn-rounded btn-sm"
                              data-mdb-ripple-init>
                        <i class="bi bi-trash"></i>
                      </button>
                    </form>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </ul>

          {% comment %}Comments{% endcomment %}


        </div>
      </div>

      <!-- Блок с заметками и задачами -->
      <div class="col-lg-4 d-flex flex-column">
        <div class="card rounded-7 p-lg-5 half-height mb-2 "
             style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;">
          <h2 class="text-center fw-bold">
            <span class="text-light">Заметки Ресурса</span>
          </h2>
          <hr class="my-3"/>
          <div class="card-body p-lg-5">
            {% for note in resource_notes|slice:"3" %}
              <div class="card rounded-6 mb-3 text-center">
                <a href="{% url 'notes:note_detail' note.id %}">
                  <p class="text-muted mt-3">
                    {{ note.title }}
                  </p>
                </a>
              </div>
            {% endfor %}
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'notes:note_list' %}?resource_id={{ object.id }}" class="btn btn-dark btn-rounded mb-2"
               data-mdb-ripple-init>Список
              заметок</a>
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'notes:note_create' %}" class="btn btn-secondary btn-rounded"
               data-mdb-ripple-init>Создать
              {#              <i class="bi bi-plus-square-fill"></i> <!-- Иконка "добавить" -->#}
            </a>
          </div>
        </div>

        <div class="card rounded-7 p-lg-5 half-height mb-2 "
             style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;">
          <h2 class="text-center fw-bold">
            <span class="text-light">Задачи Ресурса</span>
          </h2>
          <hr class="my-3"/>
          <div class="card-body p-lg-5">
            {% for task in resource_tasks|slice:":3" %}
              <div class="card rounded-6 mb-3 text-center">
                <a href="{% url 'tasks:task_detail' task.id %}">
                  <p class="text-muted mt-3">
                    {{ task.title }}
                  </p>
                </a>
              </div>
            {% endfor %}
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'tasks:task_list' %}?resource_id={{ object.id }}" class="btn btn-dark btn-rounded mb-2"
               data-mdb-ripple-init>Список
              задач</a>
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'tasks:task_create' %}" class="btn btn-secondary btn-rounded"
               data-mdb-ripple-init>Создать
              {#              <i class="bi bi-plus-square-fill"></i> <!-- Иконка "добавить" -->#}
            </a>
          </div>
        </div>

      </div>
    </div>
  </div>

{% endblock %}

to_do_list/templates/para/resource_list.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}



{% block content %}

  <div class="container">

    <section class="text-center mb-10">

      <h3 class="fw-bold mb-3 text-center">Список всех Ресурсов</h3>
      <a href="{% url 'para:resource_create' %}" class="btn btn-secondary btn-rounded mb-5" data-mdb-ripple-init>Создать
        Ресурс</a>


      <!-- Форма поиска -->
      <div class="d-flex justify-content-center align-items-center">
        <div class="col-lg-6">
          <div style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
               class="card rounded-7">
            <form method="get" class="mb-4">
              <div class="mb-3">
                <label for="id_search" class="form-label">Поиск:</label>
                <!-- Задаем классы для ширины и отступов -->
                <input type="text" name="search" id="id_search" class="form-control"
                       style="width: 80%; margin: 0 auto;"
                       placeholder="Что ищем?" value="{{ filter.form.search.value|default:'' }}">
              </div>
              <button type="submit" class="btn btn-secondary btn-rounded" data-mdb-ripple-init>Искать</button>
            </form>
          </div>
        </div>
      </div>
      <!-- Форма поиска -->

      <div class="row mt-5 gx-lg-5">

        <!-- Column -->
        {% for resource in page_obj %}
          <div class="col-lg-4 col-md-12 mb-7">

            <div class="card rounded-6 h-100">
              <div class="bg-image hover-overlay ripple mx-3 shadow-4-strong rounded-6 mt-n3"
                   data-mdb-ripple-init data-mdb-ripple-color="light">

                {% if resource.cover_image %}
                  <img src="{{ resource.cover_image.url }}" class="w-100" alt="Обложка проекта"
                       style="width: 300px; height: 365px;">
                {% else %}
                  <img src="{% static 'img/resource_card.png' %}" class="w-100"
                       alt="Обложка проекта" style="width: 300px; height: 365px;>
                {% endif %}

                <a href=" #!">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>

              <div class="card-body">
                <h5 class="card-title">{{ resource.title }}</h5>
                <a href="{% url 'para:resource_detail' resource.pk %}" class="btn btn-secondary btn-rounded"
                   data-mdb-ripple-init>Подробнее</a>
                <hr class="my-3"/>
                <p class="text-muted">
                  <small>Deadline: <u>{{ resource.deadline }}</u>;
                    Tags:
                    {% if resource.tags.all %}
                      <u>
                        {% for tag in resource.tags.all %}
                          {{ tag.title }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                      </u>
                    {% else %}
                      <span>No tags</span>
                    {% endif %}
                    {% if resource.area %}
                      Область: {{ resource.area.title }}{% if resource.area %}, {% endif %}
                    {% else %}
                      Нет области для этого ресурса.
                    {% endif %}
                    {% if resource.project %}
                      Проект: {{ resource.project.title }}{% if resource.project %}, {% endif %}
                    {% else %}
                      Нет проекта для этого ресурса.
                    {% endif %}
                  </small>
                <hr class="my-3"/>
                <p>{{ resource.description|truncatewords:50 }}</p>
                </p>
                {% if resource.author == user %}
                  <a href="{% url 'para:resource_update' resource.pk %}" class="btn btn-secondary btn-rounded"
                     data-mdb-ripple-init>Редактировать</a>
                  <a href="{% url 'para:resource_delete' resource.pk %}" class="btn btn-secondary btn-rounded"
                     data-mdb-ripple-init>Удалить</a>
                {% endif %}
              </div>
            </div>
          </div>

          <!-- Column -->
        {% empty %}
          <p>Нет Ресурсов для отображения.</p>
        {% endfor %}
      </div>
      <!-- Pagination -->
      {% include 'includes/pagination.html' %}
      <!-- Pagination -->
    </section>
  </div>
{% endblock %}
