to_do_list/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
]

to_do_list/para/urls.py
from django.urls import path

from para.views import *

app_name = 'para'

urlpatterns = [
    path('area/list/', AreaListView.as_view(), name='area_list'),
    path('area/create/', AreaCreateView.as_view(), name='area_create'),
    path('area/detail/<int:pk>/', AreaDetailView.as_view(), name='area_detail'),
    path('area/update/<int:pk>/', AreaUpdateView.as_view(), name='area_update'),
    path('area/delete/<int:pk>/', AreaDeleteView.as_view(), name='area_delete'),
    path('project/list/', ProjectListView.as_view(), name='project_list'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/detail/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/update/<int:pk>/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/delete/<int:pk>/', ProjectDeleteView.as_view(), name='project_delete'),
    path('resource/list/', ResourceListView.as_view(), name='resource_list'),
    path('resource/create/', ResourceCreateView.as_view(), name='resource_create'),
    path('resource/detail/<int:pk>/', ResourceDetailView.as_view(), name='resource_detail'),
    path('resource/update/<int:pk>/', ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/delete/<int:pk>/', ResourceDeleteView.as_view(), name='resource_delete'),
    path('dashboard/', DashBoardView.as_view(), name='dashboard'),
]

to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/', include('django.contrib.auth.urls')),
                  path('', include('core.urls')),
                  path('', include('users.urls')),
                  path('tasks/', include('tasks.urls')),
                  path('para/', include('para.urls')),
                  path('notes/', include('notes.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

to_do_list/templates/includes/footer.html
{% load static %}


  <footer class="mt-auto text-white-50">
    <p>To Do List Planner. News: <a href="https://getbootstrap.com/" class="text-white">ссылка на about</a>, by <a href="#GITHUB_link" class="text-white">eminence_saul</a>.</p>
  </footer>
</div>

to_do_list/templates/includes/footer_mdb.html
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>

to_do_list/templates/includes/header.html
{% load static %}

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#bootstrap"/>
          </svg>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'core:homepage' %}" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="{% url 'para:dashboard' %}" class="nav-link px-2 text-white">Dashboard</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
        {% if user.is_authenticated %}
          <div class="text-end">
            <button type="button" class="btn btn-warning">{{ user.username }}</button>
            <a href="{% url 'logout' %}" class="btn btn-primary" role="button" data-bs-toggle="button">Logout</a>
          </div>
        {% else %}
          <div class="text-end">
            <a href="{% url 'login' %}" class="btn btn-primary" role="button" data-bs-toggle="button">Login</a>
            <a href="#" class="btn btn-primary" role="button" data-bs-toggle="button">Sign up</a>
          </div>
        {% endif %}
      </div>
    </div>
  </header>

to_do_list/templates/includes/header_mdb.html
{% load static %}

<header>


  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark d-none d-lg-block" style="z-index: 2000;">
    <div class="container-fluid">
      <!-- Navbar brand -->
      <a class="navbar-brand nav-link" target="_blank" href="{% url 'core:homepage' %}">
        <strong>PARAplanner</strong>
      </a>
      <button class="navbar-toggler" type="button" data-mdb-collapse-init data-mdb-target="#navbarExample01"
              aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="btn btn-outline-light me-2" data-mdb-ripple-init aria-current="page"
               href="{% url 'para:dashboard' %}">{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <form method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-light" data-mdb-ripple-init role="button"
                      data-bs-toggle="button">
                Logout
              </button>
            </form>
          </li>
        </ul>
      {% else %}
        <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="btn btn-outline-light me-2" data-mdb-ripple-init aria-current="page" href="{% url 'login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-light" data-mdb-ripple-init href="{% url 'registration' %}" rel="nofollow"
               target="_blank">Регистрация</a>
          </li>
        </ul>
      {% endif %}
      <ul class="navbar-nav d-flex flex-row">
        <!-- Icons -->
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="скоро_будет" rel="nofollow" target="_blank">
            <i class="fab fa-instagram"></i>
          </a>
        </li>
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="скоро_будет" rel="nofollow" target="_blank">
            <i class="fab fa-linkedin"></i>
          </a>
        </li>
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="https://github.com/griseeminence" rel="nofollow" target="_blank">
            <i class="fab fa-github"></i>
          </a>
        </li>
      </ul>
      </div>
      </div>
  </nav>
  <!-- Navbar -->

  <!-- Background image -->
  <div id="intro" class="bg-image shadow-2-strong">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
      <div class="container d-flex align-items-center justify-content-center text-center h-100">
        <div class="text-white" data-mdb-theme="dark">
          <h1 class="mb-3">PARAplanner</h1>
          <h5 class="mb-4">Система, которая изменит вашу жизнь...</h5>
          {% if user.is_authenticated %}
            <a class="btn btn-outline-light btn-lg m-2"
               data-mdb-ripple-init href="{% url 'para:dashboard' %}"
               target="blank"
               role="button">
              Мой PP
            </a>
          {% else %}
            <a class="btn btn-outline-light btn-lg m-2"
               data-mdb-ripple-init
               href="{% url 'login' %}"
               role="button"
               rel="nofollow"
               target="_blank">
              Присоединяйся!
            </a>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
</header>

to_do_list/templates/includes/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="First">
            &laquo;&laquo;
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="Previous">
            &laquo;
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">&laquo;&laquo;</a>
        </li>
        <li class="page-item disabled">
          <a class="page-link">&laquo;</a>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_num == page_obj.number %}
          <li class="page-item active">
            <a class="page-link">{{ page_num }}</a>
          </li>
        {% elif page_num >= page_obj.number|add:-2 and page_num <= page_obj.number|add:2 %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="Next">
            &raquo;
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" aria-label="Last">
            &raquo;&raquo;
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">&raquo;</a>
        </li>
        <li class="page-item disabled">
          <a class="page-link">&raquo;&raquo;</a>
        </li>
      {% endif %}
    {% endif %}
  </ul>
</nav>

to_do_list/templates/includes/pricing.html
<section class="mb-5 mb-lg-10">

  <h3 class="fw-bold text-center mb-5">Pricing</h3>

  <div class="row gx-xl-5">
    <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">

      <div class="card">
        <div class="card-header text-center pt-4">
          <p class="text-uppercase">
            <strong>Basic</strong>
          </p>

          <h3 class="mb-4">
            <strong>$ 129</strong>
            <small class="text-muted" style="font-size: 16px">/year</small>
          </h3>

          <button type="button" class="btn btn-secondary btn-rounded w-100 mb-3">
            Buy
          </button>

        </div>
        <div class="card-body">

          <ol class="list-unstyled mb-0">
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Доступен весь основной функционал
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Размер загружаемых файлов ограничен 5 мб
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Архив ваших PARA элементов хранится до 30 дней
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Облачное хранилище до 500 мб на аккаунт
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Возможность создать не более 5 сущностей в системе PARA
            </li>
          </ol>

        </div>
      </div>

    </div>

    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">

      <div class="card">
        <div class="card-header text-center pt-4">
          <p class="text-uppercase">
            <strong>Advanced</strong>
          </p>

          <h3 class="mb-4">
            <strong>$ 299</strong>
            <small class="text-muted" style="font-size: 16px"
                   >/year</small
              >
          </h3>

          <button type="button" class="btn btn-primary btn-rounded w-100 mb-3">
            Buy
          </button>
        </div>
        <div class="card-body">
          <ol class="list-unstyled mb-0">
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Доступен весь основной функционал
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Размер загружаемых файлов ограничен 100 мб
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Архив ваших PARA элементов хранится до одного года
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Облачное хранилище до 15 гб на аккаунт
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Возможность создать неограниченное количество сущностей в системе PARA
            </li>
          </ol>
        </div>
      </div>

    </div>

    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">

      <div class="card">
        <div class="card-header text-center pt-4">
          <p class="text-uppercase">
            <strong>Enterprise</strong>
          </p>
          <h3 class="mb-4">
            <strong>$ 499</strong>
            <small class="text-muted" style="font-size: 16px"
                   >/year</small
              >
          </h3>

          <button
                  type="button"
                  class="btn btn-secondary btn-rounded w-100 mb-3"
                  >
            Buy
          </button>
        </div>
        <div class="card-body">
          <ol class="list-unstyled mb-0">
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Доступен весь основной функционал
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Размер загружаемых файлов ограничен 100 мб
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Архив ваших PARA элементов хранится до одного года
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Облачное хранилище до 15 гб на аккаунт
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Возможность создать неограниченное количество сущностей в системе PARA
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Доступ к аккаунту для всей семьи с раздельными рабочими пространствами
            </li>
            <li class="mb-3">
              <i class="fas fa-check text-success me-3"></i>Бесплатный VPN-сервис от наших партнёров. Обеспечь себе доступ из любой страны
            </li>
          </ol>
        </div>
      </div>

    </div>
  </div>

</section>