to_do_list/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
]

to_do_list/notes/urls.py
from django.urls import path

from notes.views import *

app_name = 'notes'

urlpatterns = [
    path('note/list/', NoteListView.as_view(), name='note_list'),
    path('note/create/', NoteCreateView.as_view(), name='note_create'),
    path('note/detail/<int:pk>/', NoteDetailView.as_view(), name='note_detail'),
    path('note/update/<int:pk>/', NoteUpdateView.as_view(), name='note_update'),
    path('note/delete/<int:pk>/', NoteDeleteView.as_view(), name='note_delete'),
]

to_do_list/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('list/', views.TaskListView.as_view(), name='task_list'),
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('detail/<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),
]

to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('auth/', include('django.contrib.auth.urls')),
                  path('', include('core.urls')),
                  path('', include('users.urls')),
                  path('tasks/', include('tasks.urls')),
                  path('para/', include('para.urls')),
                  path('notes/', include('notes.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

to_do_list/notes/models.py
from io import BytesIO
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django.core.files.base import ContentFile
from django.db import models
from PIL import Image

from comments.models import Comment
from core.models import ParaTag
from para.models import Area, Project, Resource

User = get_user_model()


class Note(models.Model):
    """
    The Note model represents a note associated with areas, projects, and resources
    within the PARA project. Each note contains a title, content, and optional
    tags and cover images. Notes can be associated with a specific area, project,
    or resource and can be archived.
    """

    title = models.CharField(max_length=100, verbose_name='Title')
    content = models.TextField(verbose_name='Content')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    area = models.ForeignKey(Area, on_delete=models.CASCADE, null=True, blank=True, related_name='notes')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True, related_name='notes')
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE, null=True, blank=True, related_name='notes')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    is_archived = models.BooleanField(default=False, verbose_name='Archive')
    comments = GenericRelation(Comment, content_type_field='content_type', object_id_field='object_id')
    tags = models.ManyToManyField(ParaTag, related_name='notes', blank=True, verbose_name='Tag')
    cover_image = models.ImageField(upload_to='covers/', blank=True, null=True, verbose_name='Cover Image')

    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Notes'
        ordering = ('created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """"
        Saves the note instance, processing the cover image if it exists.
        """

        if self.cover_image:
            img = Image.open(self.cover_image.file)  # Access the file object
            img = img.resize((300, 365))
            thumb_io = BytesIO()
            img.save(thumb_io, format='JPEG', quality=85)
            thumb_file = ContentFile(thumb_io.getvalue(), name=self.cover_image.name)
            self.cover_image.save(self.cover_image.name, thumb_file, save=False)

        super().save(*args, **kwargs)

to_do_list/notes/forms.py
from django import forms

from notes.models import Note


class NoteForm(forms.ModelForm):
    """
    A form for creating and updating Note instances.

    Attributes:
        new_tag (CharField): A field for entering a new tag, which is optional.
    """

    new_tag = forms.CharField(max_length=30, required=False, label="Новый тег")

    class Meta:
        model = Note
        exclude = ('author',)
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'areaTitle',
                'placeholder': 'Введите заголовок'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'id': 'areaDescription',
                'placeholder': 'Описание области',
                'rows': 5
            }),
            'is_archived': forms.CheckboxInput(attrs={
                'class': 'form-check-input',
                'type': 'checkbox',
                'id': 'loginCheck',
            }),
            'area': forms.Select(attrs={
                'class': 'form-select',
                'id': 'areaStatus'
            }),
            'project': forms.Select(attrs={
                'class': 'form-select',
                'id': 'areaStatus'
            }),
            'resource': forms.Select(attrs={
                'class': 'form-select',
                'id': 'areaStatus'
            }),
            'new_tag': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'TagTitle',
                'placeholder': 'Введите тег'
            })
        }

    def save(self, commit=True):
        """
        Save the Note instance to the database.
        (Using this to add different fields like tags and images)
        """

        instance = super().save(commit=False)

        if commit:
            instance.save()
            print(f"Заметка {instance.id} сохранена")
        return instance

to_do_list/notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from comments.forms import CommentForm
from core.models import ParaTag
from notes.filters import NoteFilter
from notes.forms import NoteForm
from notes.models import Note
from comments.utils import handle_comment_creation, handle_comment_deletion, handle_comment_editing, handle_edit_request


class NoteListView(FilterView):
    """
    A view for displaying a filtered and paginated list of notes.

    Methods:
        get_queryset(): Returns the queryset of areas, filtered by project, resource, or area if applicable.
        get_context_data(**kwargs): Extends the context with additional information if needed.
    """

    template_name = 'note/note_list.html'
    model = Note
    ordering = '-id'
    paginate_by = 6
    filterset_class = NoteFilter

    def get_queryset(self):
        """
        Fetches the task queryset. Filters tasks based on query parameters
        like project_id, resource_id, or area_id from the request's GET data.
        If no such parameter is found, it applies a general filter using the filter class.
        """

        project_id = self.request.GET.get('project_id')
        resource_id = self.request.GET.get('resource_id')
        area_id = self.request.GET.get('area_id')
        queryset = Note.objects.all()
        if project_id:
            return Note.objects.filter(project_id=project_id)
        elif resource_id:
            return Note.objects.filter(resource_id=resource_id)
        elif area_id:
            return Note.objects.filter(area_id=area_id)
        else:
            return self.filterset_class(self.request.GET, queryset=queryset).qs

    def get_context_data(self, **kwargs):
        """
        Adds additional context to the view.
        Can be extended if more data needs to be passed to the template.
        """

        context = super().get_context_data(**kwargs)
        return context


class NoteDetailView(DetailView):
    """
    A view for displaying detailed information about a specific Note, including its comments.
    Requires user authentication.

    Methods:
        get_context_data(**kwargs): Adds comments and a comment form to the context.
        post(request, *args, **kwargs): Handles various comment-related actions (creation, editing, deletion).
    """

    template_name = 'note/note_detail.html'
    redirect_url = 'notes:note_detail'
    model = Note

    def get_context_data(self, **kwargs):
        """
        Adds additional context to the template, including notes, tasks, and comments.
        """

        context = super().get_context_data(**kwargs)
        note = self.object
        context['comments'] = note.comments.filter(active=True).order_by('-created')
        context['comment_form'] = CommentForm()
        context['editing_comment'] = None
        return context

    def post(self, request, *args, **kwargs):
        """
        Handles the HTTP POST request to manage comments for the Note.

        The method processes the following actions based on the submitted form:
        - Adding a new comment
        - Editing an existing comment
        - Deleting a comment

        Note: Separate handler methods are used for each action, defined in the `comments.utils` module,
        to unify the process for different models.
        """

        self.object = self.get_object()

        if 'submit_comment' in request.POST:
            return handle_comment_creation(request, self.object, self.redirect_url)

        elif 'edit_comment' in request.POST:
            return handle_comment_editing(request, self.object, self.redirect_url)

        elif 'edit' in request.POST:
            context = handle_edit_request(request, self.object, self.get_context_data)
            if context:
                return self.render_to_response(context)

        elif 'delete_comment' in request.POST:
            return handle_comment_deletion(request, self.object, self.redirect_url)

        return self.get(request, *args, **kwargs)


class NoteCreateView(CreateView):
    """
    A view for creating a new note. Requires user authentication.

    Methods:
        form_valid(form): Processes valid form data, assigns the author, saves the image if provided,
        and adds a new tag to the note if specified.
    """

    template_name = 'note/note_create.html'
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy('notes:note_list')

    def form_valid(self, form):
        """
        Handles the saving of the note form. Assigns the current user as the notes author,
        saves the cover image if uploaded, and adds a new tag if entered by the user.
        """

        note = form.save(commit=False)
        note.author = self.request.user
        if 'cover_image' in self.request.FILES:
            note.cover_image = self.request.FILES['cover_image']
        note.save()
        form.save_m2m()
        new_tag = form.cleaned_data.get('new_tag')
        if new_tag:
            tag, created = ParaTag.objects.get_or_create(title=new_tag)
            note.tags.add(tag)
        return super().form_valid(form)


class NoteUpdateView(UpdateView):
    """
    A view for updating an existing note. Requires user authentication.
    """

    template_name = 'note/note_create.html'
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy('notes:note_list')


class NoteDeleteView(DeleteView):
    """
    A view for deleting an existing note. Requires user authentication.

    Methods:
        dispatch(request, *args, **kwargs): Ensures that only the notes author can access the delete view.
    """

    template_name = 'note/note_confirm_delete.html'
    model = Note
    success_url = reverse_lazy('notes:note_list')

    def dispatch(self, request, *args, **kwargs):
        """
        Ensures the user is the author of the note before proceeding with the request.
        """

        get_object_or_404(Note, pk=kwargs['pk'], author=request.user)
        return super().dispatch(request, *args, **kwargs)

to_do_list/templates/note/note_confirm_delete.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="d-flex justify-content-center" style="min-height: 200vh;">
    <div class="col-lg-8 text-center">
      <h2>Удалить «{{ object.title }}»?</h2>
      <div style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
           class="card rounded-7 mb-3 p-lg-5">
        <h2 class="fw-bold text-center">
          <span class="text-light">Удаляемый контент:</span>
        </h2>
        <p class="text-center fst-italic"><em>{{ object.content|truncatewords:100 }}<br></em></p>
        <form method="post">
          {% csrf_token %}

          <div class="d-flex justify-content-center mb-3 mt-5">
            <button type="submit" class="btn btn-danger btn-rounded" data-mdb-ripple-init>Удалить</button>
          </div>

        </form>
        <div class="d-flex justify-content-center">
          <a href="{% url 'tasks:task_list' %}?area_id={{ object.id }}" class="btn btn-dark btn-rounded mb-2"
             data-mdb-ripple-init>Список Заметок</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}




to_do_list/templates/note/note_create.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="text-center">
    <h1>{% if object %}Обновить Заметку{% else %}Создать Заметку{% endif %}</h1>
  </div>
  <div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="col-lg-6">
      <div style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
           class="card rounded-7 mb-3 p-lg-5">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="d-flex justify-content-center mt-4">
            <button type="submit" class="btn btn-primary mx-2">
              {% if object %}Обновить Заметку{% else %}Создать Заметку{% endif %}
            </button>
            <a href="{% url 'notes:note_list' %}" class="btn btn-secondary mx-2">Назад к списку Заметок</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

to_do_list/templates/note/note_detail.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}



{% block content %}

  <div class="container-fluid">
    <div class="row h-100">
      <!-- Блок с заметками -->
      <div class="col-lg-12 full-height">
        <div style="min-height: 1200px; background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
             class="card rounded-7 mb-3 p-lg-5">
          <h2 class="fw-bold text-center">
            <span class="text-light">{{ object.title }}</span>
          </h2>
          <p class="text-center fst-italic">
            <em>Дата создания: {{ object.created }}</em>
          </p>
          <p class="text-center fst-italic">
            <em>Теги:
              {% if object.tags.all %}
                {% for tag in object.tags.all %}
                  {{ tag.title }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              {% else %}
                <span>Нет тегов</span>
              {% endif %}
            </em>
          </p>

          <hr class="my-3"/>
          <div class="card-body">
            <p class="text-muted mb-4">
              {{ object.content }}
            </p>

          </div>

          <hr class="my-3"/>
          <div class="d-flex justify-content-center">
            <a href="{% url 'notes:note_list' %}" class="btn btn-dark btn-rounded mb-2" data-mdb-ripple-init>Список
              Заметок</a>
          </div>
          <div class="d-flex justify-content-center">
            <a href="{% url 'notes:note_update' object.pk %}" class="btn btn-warning btn-rounded mb-2 me-1"
               data-mdb-ripple-init>
              <i class="bi bi-pencil"></i>
            </a>
            <a href="{% url 'notes:note_delete' object.pk %}" class="btn btn-danger btn-rounded mb-2"
               data-mdb-ripple-init>
              <i class="bi bi-trash"></i>
            </a>
          </div>


          {% comment %}Comments{% endcomment %}
          <hr class="my-3"/>

          {% if editing_comment %}
            <form method="POST">
              {% csrf_token %}
              <input type="hidden" name="comment_id" value="{{ editing_comment.id }}">
              {{ comment_form.text.label }}  <!-- Заголовок поля -->
              {{ comment_form.text }}  <!-- Поле ввода текста с предзаполненным значением -->
              <div class="d-flex justify-content-center mb-3 mt-3">
                <button type="submit" name="edit_comment" class="btn btn-secondary btn-rounded" data-mdb-ripple-init>
                  Редактировать
                </button>
              </div>
            </form>
          {% else %}
            <form method="POST">
              {% csrf_token %}
              {{ comment_form.as_p }}
              <div class="d-flex justify-content-center mb-3 mt-3">
                <button type="submit" name="submit_comment" class="btn btn-secondary btn-rounded" data-mdb-ripple-init>
                  Опубликовать
                </button>
              </div>
            </form>
          {% endif %}

          <br>
          <ul>
            {% for comment in comments %}
              <div class="card mb-3">
                <div class="card-body">
                  <p>{{ comment.text }}</p>
                  <small>Автор: {{ comment.author }} | Дата: {{ comment.created }}</small>
                  <!-- Форма редактирования комментария -->
                  {% if comment.author == request.user %}
                    <form method="post" style="display:inline;">
                      {% csrf_token %}
                      <input type="hidden" name="comment_id" value="{{ comment.id }}">
                      <button type="submit" name="edit" class="btn btn-warning btn-rounded btn-sm"
                              data-mdb-ripple-init>
                        <i class="bi bi-pencil"></i>
                      </button>
                    </form>
                    <!-- Форма удаления комментария -->
                    <form method="post" style="display:inline;">
                      {% csrf_token %}
                      <input type="hidden" name="comment_id" value="{{ comment.id }}">
                      <button type="submit" name="delete_comment" class="btn btn-danger btn-rounded btn-sm"
                              data-mdb-ripple-init>
                        <i class="bi bi-trash"></i>
                      </button>
                    </form>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </ul>

          {% comment %}Comments{% endcomment %}


        </div>
      </div>
    </div>
  </div>

{% endblock %}

to_do_list/templates/note/note_list.html
{% extends "base_mdb.html" %}
{% load static %}
{% load django_bootstrap5 %}


{% block content %}

  <div class="container">
    <section class="text-center mb-10">
      <h3 class="fw-bold mb-3 text-center">Список всех Заметок</h3>
      <a href="{% url 'notes:note_create' %}" class="btn btn-secondary btn-rounded mb-5" data-mdb-ripple-init>Создать
        Заметку</a>


      <!-- Форма поиска -->
      <div class="d-flex justify-content-center align-items-center">
        <div class="col-lg-6">
          <div style="background: hsla(0, 0%, 100%, 0.15); backdrop-filter: blur(30px); z-index: 1;"
               class="card rounded-7">
            <form method="get" class="mb-4">
              <div class="mb-3">
                <label for="id_search" class="form-label">Поиск:</label>
                <!-- Задаем классы для ширины и отступов -->
                <input type="text" name="search" id="id_search" class="form-control"
                       style="width: 80%; margin: 0 auto;"
                       placeholder="Что ищем?" value="{{ filter.form.search.value|default:'' }}">
              </div>
              <button type="submit" class="btn btn-secondary btn-rounded" data-mdb-ripple-init>Искать</button>
            </form>
          </div>
        </div>
      </div>
      <!-- Форма поиска -->


      <div class="row mt-5 gx-lg-5">
        <!-- Column -->
        {% for note in object_list %}
          <div class="col-lg-4 col-md-12 mb-7">
            <div class="card rounded-6 h-100">
              <div class="bg-image hover-overlay ripple mx-3 shadow-4-strong rounded-6 mt-n3"
                   data-mdb-ripple-init data-mdb-ripple-color="light">

                {% if note.cover_image %}
                  <img src="{{ note.cover_image.url }}" class="w-100" alt="Обложка проекта"
                       style="width: 300px; height: 365px;">
                {% else %}
                  <img src="{% static 'img/note_card.png' %}" class="w-100"
                       alt="Обложка проекта" style="width: 300px; height: 365px;>
                {% endif %}

                <a href=" #!">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ note.title }}</h5>
                <a href="{% url 'notes:note_detail' note.pk %}" class="btn btn-secondary btn-rounded"
                   data-mdb-ripple-init>Подробнее</a>
                <hr class="my-3"/>
                <p class="text-muted">
                  <small>
                    Deadline: <u>{{ note.deadline }}</u>;
                    Tags:
                    {% if note.tags.all %}
                      <u>
                        {% for tag in note.tags.all %}
                          {{ tag.title }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                      </u>
                    {% else %}
                      <span>No tags</span>
                    {% endif %}
                    {% if note.area %}
                      Область: {{ note.area.title }}{% if note.area %}, {% endif %}
                    {% else %}
                      Нет области для этой заметки.
                    {% endif %}
                    {% if note.project %}
                      Проект: {{ note.project.title }}{% if note.project %}, {% endif %}
                    {% else %}
                      Нет проекта для этой заметки.
                    {% endif %}
                  </small>
                <hr class="my-3"/>
                <p>{{ note.description|truncatewords:50 }}</p>
                </p>
                {% if note.author == user %}
                  <a href="{% url 'notes:note_update' note.pk %}" class="btn btn-secondary btn-rounded"
                     data-mdb-ripple-init>Редактировать</a>
                  <a href="{% url 'notes:note_delete' note.pk %}" class="btn btn-secondary btn-rounded"
                     data-mdb-ripple-init>Удалить</a>
                {% endif %}
              </div>
            </div>
          </div>
          <!-- Column -->
        {% empty %}
          <p>Нет Заметок для отображения.</p>
        {% endfor %}
      </div>
      <!-- Pagination -->
      {% include 'includes/pagination.html' %}
      <!-- Pagination -->
    </section>
  </div>

{% endblock %}